---
title: "Modeling"
author: "Ethan Shen"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(caret)
library(e1071) 
library(zoo)
```

```{r}
PL_data = read_csv("premier_league_data.csv") 
PL_data <- PL_data %>%
  mutate(HT_Points = case_when(
    FTR == "H" ~ 3,
    FTR == "D" ~ 1,
    FTR == "A" ~ 0
  ),
  AT_Points = case_when(
    FTR == "A" ~ 3,
    FTR == "D" ~ 1,
    FTR == "H" ~ 0
  )) %>%
  dplyr::select(-Div, -HTR, -Referee, -FTHG, -FTAG, -HTHG, -HTAG) %>%
  dplyr::select(Date, HT_Points, AT_Points, everything()) %>%
  mutate(Date = dmy(Date)) %>%
  filter(Date >= "2010-07-14")
```


```{r}
cols <- colnames(PL_data)
away_all <- PL_data[grep(c("^[^H]"), cols)] %>%
  mutate(home_away = "Away") %>%
  mutate(win_loss = case_when(
    AT_Points == 3 ~ 1,
    AT_Points == 1 ~ 0,
    AT_Points == 0 ~ -1
  )) %>%
  select(win_loss, everything())
home_all <- PL_data[grep(c("^[^A]"), cols)] %>%
  mutate(home_away = "Home") %>%
  mutate(win_loss = case_when(
    HT_Points == 3 ~ 1,
    HT_Points == 1 ~ 0,
    HT_Points == 0 ~ -1
  )) %>%
  select(win_loss, everything())

new_col_names = c("win_loss", "date", "points", "team", "full_time_results", "shots", "shots_on_target", "fouls", "corners", "yellow_cards", "red_cards", "home_away")
names(away_all) <- new_col_names
names(home_all) <- new_col_names
```

```{r}
PL_data_combined <- rbind(home_all, away_all) %>%
  mutate(season = case_when(
    date >= "2018-08-01" & date <= "2019-06-01" ~ "2018-2019",
    date >= "2017-08-01" & date <= "2018-06-01" ~ "2017-2018",
    date >= "2016-08-01" & date <= "2017-06-01" ~ "2016-2017",
    date >= "2015-08-01" & date <= "2016-06-01" ~ "2015-2016",
    date >= "2014-08-01" & date <= "2015-06-01" ~ "2014-2015",
    date >= "2013-08-01" & date <= "2014-06-01" ~ "2013-2014",
    date >= "2012-08-01" & date <= "2013-06-01" ~ "2012-2013",
    date >= "2011-08-01" & date <= "2012-06-01" ~ "2011-2012",
    date >= "2010-08-01" & date <= "2011-06-01" ~ "2010-2011"
  )) %>%
  group_by(season) %>%
  arrange(date) %>%
  ungroup() %>%
  group_by(season, team) %>%
  mutate(sums = zoo::rollsumr(points, k=5, fill=NA),
         win_loss = as.factor(win_loss)) %>%
  arrange(desc(season), team) %>%
  ungroup() %>%
  mutate(Group = rep(1:(n()/38), each = 38)) 

PL_data_combined 
```

```{r}
win_streak = c(if_else(PL_data_combined[1,]$win_loss == 1, 1, 0))
wins = 0

for (row in 2:nrow(PL_data_combined)) {
  if (PL_data_combined[row,]$Group == PL_data_combined[row-1,]$Group) {
    if (PL_data_combined[row,]$points == 3) {
      wins = wins + 1
      win_streak = c(win_streak, wins)
    } else {
      wins = 0
      win_streak = c(win_streak, wins)
    }
  } else {
    wins = 0
    if (PL_data_combined[row,]$points == 3) {
      wins = wins + 1
      win_streak = c(win_streak, wins)
    } else {
      wins = 0
      win_streak = c(win_streak, wins)
    }
  }
}

PL_data_combined$win_streak <- win_streak
```

```{r}
unbeaten_streak = c(if_else(PL_data_combined[1,]$win_loss == -1, 0, 1))
unbeaten = 0
for (row in 2:nrow(PL_data_combined)) {
  if (PL_data_combined[row,]$Group == PL_data_combined[row-1,]$Group) {
    if (PL_data_combined[row,]$points == 3 | PL_data_combined[row,]$points == 1) {
      unbeaten = unbeaten + 1
      unbeaten_streak = c(unbeaten_streak, unbeaten)
    } else {
      unbeaten = 0
      unbeaten_streak = c(unbeaten_streak, unbeaten)
    }
  } else {
    unbeaten = 0
    if (PL_data_combined[row,]$points == 3 | PL_data_combined[row,]$points == 1) {
      unbeaten = unbeaten + 1
      unbeaten_streak = c(unbeaten_streak, unbeaten)
    } else {
      unbeaten = 0
      unbeaten_streak = c(unbeaten_streak, unbeaten)
    }
  }
}

PL_data_combined$unbeaten_streak <- unbeaten_streak
```

```{r}
PL_data_modeling <- PL_data_combined %>%
  arrange(desc(season), date) %>%
  select(-full_time_results, -home_away, -Group, -season, -points)
```

### Train/Test Data 

```{r}
training <- PL_data_modeling %>%
  filter(date < "2018-08-10") %>%
  na.omit()

testing <- PL_data_modeling %>%
  filter(date >= "2018-08-10") %>%
  na.omit()
```


```{r}
set.seed(123)

rf_control <- trainControl(method="repeatedcv", 
                           number=10, 
                           repeats=5,
                           search = "grid")
rf_grid <- expand.grid(mtry = c(1:(ncol(training) - 5)))
rf_baseline <- train(win_loss ~ .- date - team - win_streak - unbeaten_streak,
                   data = training,
                   method = "rf", 
                   metric = "Accuracy", 
                   trControl = rf_control,
                   tuneGrid = rf_grid)
print((rf_random))
confusionMatrix(rf_random)
plot(rf_random)

y_pred = predict(rf_random, testing)
cm.rf=table(y_pred,as.factor(testing$win_loss))
cm.rf
sum(diag(cm.rf))/sum(cm.rf)



library(randomForest)

rf <- randomForest(win_loss ~ .- date - team - win_streak - unbeaten_streak, 
                   data=training)

y_pred = predict(rf, testing)
cm.rf=table(y_pred,as.factor(testing$win_loss))
cm.rf
sum(diag(cm.rf))/sum(cm.rf)
varImpPlot(rf)

control_grid <- trainControl(method="repeatedcv", number=5, repeats=3, search="grid")
set.seed(123)
tunegrid <- expand.grid(.mtry=c(1:9))
rf_gridsearch <- train(win_loss ~ .- date - team - win_streak - unbeaten_streak,
                       data=training, 
                       method="rf", 
                       metric=metric, 
                       tuneGrid=tunegrid, 
                       trControl=control_grid)
print(rf_gridsearch)
plot(rf_gridsearch)
```

```{r warning=FALSE, message=FALSE}
set.seed(123)
features <- setdiff(names(training), "win_loss")
x <- training[, features]
x <- x %>%
  dplyr::select(-team, -date, -win_streak, -unbeaten_streak) 
y <- training$win_loss

train_control <- trainControl(
  method = "repeatedcv",
  number = 10,
  repeats = 5, 
  search = "grid")

nb.m1 <- caret::train(
  x = x,
  y = y,
  method = "nb",
  trControl = train_control,
  na.action=na.omit
)
confusionMatrix(nb.m1)
plot(nb.m1)

search_grid <- expand.grid(
  usekernel = c(TRUE, FALSE),
  fL = 0:5,
  adjust = seq(0, 5, by = 1)
)

as.matrix(cm.nb)
# train model
nb.m2 <- train(
  x = x,
  y = y,
  method = "nb",
  trControl = train_control,
  tuneGrid = search_grid
  )

print(nb.m2)
 print(rf_baseline)
NB_pred <- predict(nb.m1, testing)

cm.nb=table(NB_pred, testing$win_loss)
cm.nb
sum(diag(cm.nb))/sum(cm.nb)

```

```{r}
set.seed(123)
kernels = c("linear", "polynomial", "radial", "sigmoid")
types = c("C-classification", "nu-classification")

for (kernel in kernels) {
  for (type in types) {
    SVM = svm(formula = win_loss ~ .- date - team - win_streak - unbeaten_streak, 
              data = training, 
              type = type, 
              kernel = kernel) 
    SVM_pred = predict(SVM, newdata = testing) 
    cm = table(SVM_pred, testing$win_loss)
    cr = sum(diag(cm))/sum(cm)
    print(paste(type, "," ,kernel, "," , cr));
  }
}

SVM = svm(formula = win_loss ~ .- date - team - win_streak - unbeaten_streak, 
          data = training, 
          type = "C-classification", 
          kernel = "radial") 
summary(SVM)
SVM_pred = predict(SVM, newdata = testing) 
cm.svm = table(SVM_pred, testing$win_loss)
cm.svm
sum(diag(cm.svm))/sum(cm.svm)
```


