---
title: "shiny"
author: "Ethan Shen"
Date: "5/7/2020"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(shiny)
library(shinydashboard)
```


```{r}
PL_data_app = read_csv("premier_league_data.csv") 

PL_data_app <- PL_data_app %>%
  mutate(Date = dmy(Date)) %>%
  filter(Date >= "2010-07-14") %>%
  mutate(HT_Points = case_when(
           FTR == "H" ~ 3,
           FTR == "D" ~ 1,
           FTR == "A" ~ 0
         ),
         AT_Points = case_when(
           FTR == "A" ~ 3,
           FTR == "D" ~ 1,
           FTR == "H" ~ 0
         ),
         Season = case_when(
           Date >= "2018-08-01" & Date <= "2019-06-01" ~ "2018-2019",
           Date >= "2017-08-01" & Date <= "2018-06-01" ~ "2017-2018",
           Date >= "2016-08-01" & Date <= "2017-06-01" ~ "2016-2017",
           Date >= "2015-08-01" & Date <= "2016-06-01" ~ "2015-2016",
           Date >= "2014-08-01" & Date <= "2015-06-01" ~ "2014-2015",
           Date >= "2013-08-01" & Date <= "2014-06-01" ~ "2013-2014",
           Date >= "2012-08-01" & Date <= "2013-06-01" ~ "2012-2013",
           Date >= "2011-08-01" & Date <= "2012-06-01" ~ "2011-2012",
           Date >= "2010-08-01" & Date <= "2011-06-01" ~ "2010-2011"
         )
  )
```

```{r}
home_points_app <- PL_data_app %>%
  select(Date, HomeTeam, HT_Points, Season) %>%
  rename(Team = HomeTeam,
         FT_Points = HT_Points)

away_points_app <- PL_data_app %>%
  select(Date, AwayTeam, AT_Points, Season) %>%
  rename(Team = AwayTeam,
         FT_Points = AT_Points)
```

```{r}
team_points_app <- rbind(home_points_app, away_points_app) %>%
  arrange(Date) %>%
  group_by(Team, Season) %>%
  mutate(cumpoints = cumsum(FT_Points)) %>%
  mutate(final_id = row_number()) %>%
  arrange(desc(Season), Team, Date) 

top6teams_points_app <- team_points_app %>%
  group_by(Team, Season) %>%
  filter(cumpoints == max(cumpoints) & final_id == max(final_id)) %>%
  arrange(desc(Season), desc(cumpoints))
```


```{r}
ui <- fluidPage(
  
)


server <- function(input, output) {
  
  
}

shinyApp(ui = ui, server = server)

```

